use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Trace-owned dataset manifest describing the Parquet objects for a pinned dataset version.
///
/// Notes:
/// - This is not a Cryo artifact; it is generated by trusted ingestion code after producing Parquet.
/// - Treat as untrusted input when consumed (size limits + strict schema validation + authz checks).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DatasetManifestV1 {
    /// Manifest schema version.
    pub version: u32,

    pub dataset_uuid: Uuid,
    pub dataset_version: Uuid,

    /// Parquet object keys (relative to the S3 bucket).
    ///
    /// Backwards compatibility: older manifests may use the name `parquet_objects`.
    #[serde(alias = "parquet_objects")]
    pub parquet_keys: Vec<String>,
}

impl DatasetManifestV1 {
    pub const VERSION: u32 = 1;
}
